# Generated by Django 2.2.4 on 2019-08-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_reset_code'),
        ('carddecks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.TextField(max_length=100),
        ),
    ]
