# Generated by Django 2.2.4 on 2019-08-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carddecks', '0003_deck_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='users',
            new_name='user',
        ),
    ]
