# Generated by Django 2.2.4 on 2019-08-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carddecks', '0005_auto_20190831_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(db_column='email', default='', on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
