# Generated by Django 2.2.4 on 2019-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddecks', '0006_auto_20190831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
