# Generated by Django 2.2.4 on 2019-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddecks', '0007_deck_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
